from __future__ import annotations

from typing import Any

RAW_SCHEMAS = {
    "clickstream_events": {
        "description": "Raw clickstream events generated by the storefront simulator.",
        "required": ["event_id", "event_type", "user_id"],
        "types": {
            "event_id": str,
            "event_type": str,
            "user_id": (int, str),
            "ts": str,
            "event_time": str,
            "amount": (int, float),
        },
    },
    "server_logs": {
        "description": "Raw application server log records for operational monitoring.",
        "required": ["message"],
        "types": {
            "timestamp": str,
            "level": str,
            "message": str,
        },
    },
    "order_changes": {
        "description": "Raw order status and order lifecycle updates from PostgreSQL.",
        "required": ["order_id", "order_status", "order_placed_at"],
        "types": {
            "order_id": (int, str),
            "order_status": str,
            "order_placed_at": str,
            "user_id": (int, str),
            "product_id": (int, str),
            "total_amount": (int, float),
        },
    },
    "shipment_data": {
        "description": "Raw shipment payloads captured from the mock shipping API.",
        "required": ["order_id", "status", "status_last_updated_at"],
        "types": {
            "order_id": (int, str),
            "status": str,
            "status_last_updated_at": str,
            "carrier": str,
            "tracking_number": str,
        },
    },
}


def validate_records(source_name: str, records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Validate raw Bronze records against the Phase 2 raw schema contract.

    The function ensures each record contains the required raw fields and uses the
    expected primitive types before the records are written into Bronze storage.
    """
    if source_name not in RAW_SCHEMAS:
        raise ValueError(f"Unknown Bronze source schema: {source_name}")

    schema = RAW_SCHEMAS[source_name]
    validated: list[dict[str, Any]] = []

    for index, record in enumerate(records):
        candidate = record

        if isinstance(record, str) and source_name == "server_logs":
            candidate = {"message": record}

        if not isinstance(candidate, dict):
            raise ValueError(f"Invalid record at index {index} for {source_name}: expected an object")

        if source_name == "clickstream_events" and "ts" not in candidate and "event_time" in candidate:
            candidate = {**candidate, "ts": candidate["event_time"]}

        missing_fields = [field for field in schema["required"] if field not in candidate or candidate[field] in (None, "")]
        if missing_fields:
            raise ValueError(
                f"Invalid record at index {index} for {source_name}: missing required fields {missing_fields}"
            )

        expected_types = schema.get("types", {})
        for field_name, expected_type in expected_types.items():
            if field_name in candidate and candidate[field_name] is not None:
                if isinstance(expected_type, tuple):
                    if not isinstance(candidate[field_name], expected_type):
                        raise ValueError(
                            f"Invalid record at index {index} for {source_name}: field '{field_name}' must be one of {expected_type}"
                        )
                elif not isinstance(candidate[field_name], expected_type):
                    raise ValueError(
                        f"Invalid record at index {index} for {source_name}: field '{field_name}' must be of type {expected_type.__name__}"
                    )

        validated.append(candidate)

    return validated
